// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OctavaPrueba.Models;

#nullable disable

namespace OctavaPrueba.Migrations
{
    [DbContext(typeof(BdMiradorContext))]
    [Migration("20241105053120_actualizacion")]
    partial class Actualizacion 
    {
    }
}
