// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OctavaPrueba.Models;

#nullable disable

namespace OctavaPrueba.Migrations
{
    [DbContext(typeof(BdMiradorContext))]
    partial class BdMiradorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OctavaPrueba.Models.Abono", b =>
                {
                    b.Property<int>("IdAbono")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAbono"));

                    b.Property<double>("CantAbono")
                        .HasColumnType("float");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaAbono")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdReserva")
                        .HasColumnType("int");

                    b.Property<double>("Iva")
                        .HasColumnType("float")
                        .HasColumnName("IVA");

                    b.Property<double>("Pendiente")
                        .HasColumnType("float");

                    b.Property<double>("Porcentaje")
                        .HasColumnType("float");

                    b.Property<double>("SubTotal")
                        .HasColumnType("float");

                    b.Property<double>("ValorDeuda")
                        .HasColumnType("float");

                    b.HasKey("IdAbono")
                        .HasName("PK__Abono__A4693DA7ACAE2F13");

                    b.HasIndex("IdReserva");

                    b.ToTable("Abono", (string)null);
                });

            modelBuilder.Entity("OctavaPrueba.Models.Cliente", b =>
                {
                    b.Property<string>("NroDocumento")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Apellidos")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Celular")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Contrasena")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("IdRol")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoDocumento")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("NroDocumento")
                        .HasName("PK__Clientes__CC62C91C1295F1B0");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdTipoDocumento");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("OctavaPrueba.Models.DetalleReservaPaquete", b =>
                {
                    b.Property<int>("IdReserva")
                        .HasColumnType("int");

                    b.Property<int>("IdPaquete")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("DetalleReservaPaquete1")
                        .HasColumnType("int")
                        .HasColumnName("DetalleReservaPaquete");

                    b.Property<int?>("PaqueteIdPaquete")
                        .HasColumnType("int");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.HasKey("IdReserva", "IdPaquete");

                    b.HasIndex("IdPaquete");

                    b.HasIndex("PaqueteIdPaquete");

                    b.ToTable("DetalleReservaPaquete", (string)null);
                });

            modelBuilder.Entity("OctavaPrueba.Models.DetalleReservaServicio", b =>
                {
                    b.Property<int>("IdReserva")
                        .HasColumnType("int");

                    b.Property<int>("IdServicio")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("IdDetalleReservaServicio")
                        .HasColumnType("int");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.Property<int?>("ServicioIdServicio")
                        .HasColumnType("int");

                    b.HasKey("IdReserva", "IdServicio");

                    b.HasIndex("IdServicio");

                    b.HasIndex("ServicioIdServicio");

                    b.ToTable("DetalleReservaServicio", (string)null);
                });

            modelBuilder.Entity("OctavaPrueba.Models.EstadosReserva", b =>
                {
                    b.Property<int>("IdEstadoReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoReserva"));

                    b.Property<string>("NombreEstadoReserva")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("IdEstadoReserva")
                        .HasName("PK__EstadosR__3E654CA800F17936");

                    b.ToTable("EstadosReserva", (string)null);
                });

            modelBuilder.Entity("OctavaPrueba.Models.HabitacionMueble", b =>
                {
                    b.Property<int>("IdHabitacionMueble")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHabitacionMueble"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("IdHabitacion")
                        .HasColumnType("int");

                    b.Property<int>("IdMueble")
                        .HasColumnType("int");

                    b.HasKey("IdHabitacionMueble")
                        .HasName("PK__Habitaci__402E049DE25E461D");

                    b.HasIndex("IdHabitacion");

                    b.HasIndex("IdMueble");

                    b.ToTable("HabitacionMueble", (string)null);
                });

            modelBuilder.Entity("OctavaPrueba.Models.Habitacione", b =>
                {
                    b.Property<int>("IdHabitacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHabitacion"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdTipoHabitacion")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdHabitacion")
                        .HasName("PK__Habitaci__8BBBF90152428C64");

                    b.HasIndex("IdTipoHabitacion");

                    b.ToTable("Habitaciones");
                });

            modelBuilder.Entity("OctavaPrueba.Models.ImagenAbono", b =>
                {
                    b.Property<int>("IdImagenAbono")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImagenAbono"));

                    b.Property<int>("IdAbono")
                        .HasColumnType("int");

                    b.Property<int>("IdImagen")
                        .HasColumnType("int");

                    b.HasKey("IdImagenAbono")
                        .HasName("PK__ImagenAb__A40FAE53925F394B");

                    b.HasIndex("IdAbono");

                    b.HasIndex("IdImagen");

                    b.ToTable("ImagenAbono", (string)null);
                });

            modelBuilder.Entity("OctavaPrueba.Models.ImagenHabitacion", b =>
                {
                    b.Property<int>("IdImagenHabi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImagenHabi"));

                    b.Property<int>("IdHabitacion")
                        .HasColumnType("int");

                    b.Property<int>("IdImagen")
                        .HasColumnType("int");

                    b.HasKey("IdImagenHabi")
                        .HasName("PK__ImagenHa__5B5FF6AD8470DF56");

                    b.HasIndex("IdHabitacion");

                    b.HasIndex("IdImagen");

                    b.ToTable("ImagenHabitacion", (string)null);
                });

            modelBuilder.Entity("OctavaPrueba.Models.ImagenPaquete", b =>
                {
                    b.Property<int>("IdImagenPaque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImagenPaque"));

                    b.Property<int>("IdImagen")
                        .HasColumnType("int");

                    b.Property<int>("IdPaquete")
                        .HasColumnType("int");

                    b.HasKey("IdImagenPaque")
                        .HasName("PK__ImagenPa__AD53DF94C1FC3BEB");

                    b.HasIndex("IdImagen");

                    b.HasIndex("IdPaquete");

                    b.ToTable("ImagenPaquete", (string)null);
                });

            modelBuilder.Entity("OctavaPrueba.Models.ImagenServicio", b =>
                {
                    b.Property<int>("IdImagenServi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImagenServi"));

                    b.Property<int>("IdImagen")
                        .HasColumnType("int");

                    b.Property<int>("IdServicio")
                        .HasColumnType("int");

                    b.HasKey("IdImagenServi")
                        .HasName("PK__ImagenSe__3C03784C13A0C448");

                    b.HasIndex("IdImagen");

                    b.HasIndex("IdServicio");

                    b.ToTable("ImagenServicio", (string)null);
                });

            modelBuilder.Entity("OctavaPrueba.Models.Imagene", b =>
                {
                    b.Property<int>("IdImagen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImagen"));

                    b.Property<string>("UrlImagen")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdImagen")
                        .HasName("PK__Imagenes__B42D8F2AE345C7C8");

                    b.ToTable("Imagenes");
                });

            modelBuilder.Entity("OctavaPrueba.Models.MetodoPago", b =>
                {
                    b.Property<int>("IdMetodoPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMetodoPago"));

                    b.Property<string>("NomMetodoPago")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdMetodoPago")
                        .HasName("PK__MetodoPa__6F49A9BE655372DA");

                    b.ToTable("MetodoPago", (string)null);
                });

            modelBuilder.Entity("OctavaPrueba.Models.Mueble", b =>
                {
                    b.Property<int>("IdMueble")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMueble"));

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<byte[]>("Imagen")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdMueble")
                        .HasName("PK__Muebles__829D15E897CA2D58");

                    b.ToTable("Muebles");
                });

            modelBuilder.Entity("OctavaPrueba.Models.Paquete", b =>
                {
                    b.Property<int>("IdPaquete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPaquete"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("IdHabitacion")
                        .HasColumnType("int");

                    b.Property<string>("NomPaquete")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("IdPaquete")
                        .HasName("PK__Paquetes__DE278F8B4B19D424");

                    b.HasIndex("IdHabitacion");

                    b.ToTable("Paquetes");
                });

            modelBuilder.Entity("OctavaPrueba.Models.PaqueteServicio", b =>
                {
                    b.Property<int>("IdPaqueteServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPaqueteServicio"));

                    b.Property<int>("IdPaquete")
                        .HasColumnType("int");

                    b.Property<int>("IdServicio")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("IdPaqueteServicio")
                        .HasName("PK__PaqueteS__DE5C2BC269981C11");

                    b.HasIndex("IdPaquete");

                    b.HasIndex("IdServicio");

                    b.ToTable("PaqueteServicio", (string)null);
                });

            modelBuilder.Entity("OctavaPrueba.Models.Permiso", b =>
                {
                    b.Property<int>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPermiso"));

                    b.Property<string>("NomPermiso")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdPermiso")
                        .HasName("PK__Permisos__0D626EC8EE2AA9B9");

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("OctavaPrueba.Models.PermisosRole", b =>
                {
                    b.Property<int>("IdPermisosRoles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPermisosRoles"));

                    b.Property<int?>("IdPermiso")
                        .HasColumnType("int");

                    b.Property<int?>("IdRol")
                        .HasColumnType("int");

                    b.HasKey("IdPermisosRoles")
                        .HasName("PK__Permisos__8C257ED946E43BA0");

                    b.HasIndex("IdPermiso");

                    b.HasIndex("IdRol");

                    b.ToTable("PermisosRoles");
                });

            modelBuilder.Entity("OctavaPrueba.Models.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReserva"));

                    b.Property<double>("Descuento")
                        .HasColumnType("float");

                    b.Property<DateTime>("FechaFinalizacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdEstadoReserva")
                        .HasColumnType("int");

                    b.Property<double>("Iva")
                        .HasColumnType("float")
                        .HasColumnName("IVA");

                    b.Property<int>("MetodoPago")
                        .HasColumnType("int");

                    b.Property<double>("MontoTotal")
                        .HasColumnType("float");

                    b.Property<string>("NroDocumentoCliente")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("NroPersonas")
                        .HasColumnType("int");

                    b.Property<double>("SubTotal")
                        .HasColumnType("float");


                    b.HasKey("IdReserva")
                        .HasName("PK__Reservas__0E49C69DAAB54F8D");

                    b.HasIndex("IdEstadoReserva");

                    b.HasIndex("MetodoPago");

                    b.HasIndex("NroDocumentoCliente");

                  

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("OctavaPrueba.Models.Role", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("NomRol")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdRol")
                        .HasName("PK__Roles__2A49584CF41CEB44");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("OctavaPrueba.Models.Servicio", b =>
                {
                    b.Property<int>("IdServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdServicio"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("IdTipoServicio")
                        .HasColumnType("int");

                    b.Property<string>("NomServicio")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("IdServicio")
                        .HasName("PK__Servicio__2DCCF9A2E133ADCB");

                    b.HasIndex("IdTipoServicio");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("OctavaPrueba.Models.TipoDocumento", b =>
                {
                    b.Property<int>("IdTipoDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoDocumento"));

                    b.Property<string>("NomTipoDcumento")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdTipoDocumento")
                        .HasName("PK__TipoDocu__3AB3332FC9A90625");

                    b.ToTable("TipoDocumento", (string)null);
                });

            modelBuilder.Entity("OctavaPrueba.Models.TipoHabitacione", b =>
                {
                    b.Property<int>("IdTipoHabitacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoHabitacion"));

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NomTipoHabitacion")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("NumeroPersonas")
                        .HasColumnType("int");

                    b.HasKey("IdTipoHabitacion")
                        .HasName("PK__TipoHabi__AB75E87C343675F0");

                    b.ToTable("TipoHabitaciones");
                });

            modelBuilder.Entity("OctavaPrueba.Models.TipoServicio", b =>
                {
                    b.Property<int>("IdTipoServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoServicio"));

                    b.Property<string>("NombreTipoServicio")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdTipoServicio")
                        .HasName("PK__TipoServ__E29B3EA7B64AE76B");

                    b.ToTable("TipoServicios");
                });

            modelBuilder.Entity("OctavaPrueba.Models.Usuario", b =>
                {
                    b.Property<int>("NroDocumento")
                        .HasColumnType("int");

                    b.Property<string>("Apellidos")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Celular")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Contrasena")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("IdRol")
                        .HasColumnType("int");

                    b.Property<int?>("IdTipoDocumento")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("NroDocumento")
                        .HasName("PK__Usuarios__CC62C91CF0D2702F");

                    b.HasIndex("IdRol");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("OctavaPrueba.Models.Abono", b =>
                {
                    b.HasOne("OctavaPrueba.Models.Reserva", "IdReservaNavigation")
                        .WithMany("Abonos")
                        .HasForeignKey("IdReserva")
                        .IsRequired()
                        .HasConstraintName("FK__Abono__IdReserva__19DFD96B");

                    b.Navigation("IdReservaNavigation");
                });

            modelBuilder.Entity("OctavaPrueba.Models.Cliente", b =>
                {
                    b.HasOne("OctavaPrueba.Models.Role", "IdRolNavigation")
                        .WithMany("Clientes")
                        .HasForeignKey("IdRol")
                        .HasConstraintName("FK__Clientes__IdRol__02084FDA");

                    b.HasOne("OctavaPrueba.Models.TipoDocumento", "IdTipoDocumentoNavigation")
                        .WithMany("Clientes")
                        .HasForeignKey("IdTipoDocumento")
                        .IsRequired()
                        .HasConstraintName("FK__Clientes__IdTipo__02FC7413");

                    b.Navigation("IdRolNavigation");

                    b.Navigation("IdTipoDocumentoNavigation");
                });

            modelBuilder.Entity("OctavaPrueba.Models.DetalleReservaPaquete", b =>
                {
                    b.HasOne("OctavaPrueba.Models.Paquete", "IdPaqueteNavigation")
                        .WithMany()
                        .HasForeignKey("IdPaquete")
                        .IsRequired()
                        .HasConstraintName("FK__DetalleRe__IdPaq__14270015");

                    b.HasOne("OctavaPrueba.Models.Reserva", "IdReservaNavigation")
                        .WithMany("DetalleReservaPaquetes")
                        .HasForeignKey("IdReserva")
                        .IsRequired()
                        .HasConstraintName("FK__DetalleRe__IdRes__151B244E");

                    b.HasOne("OctavaPrueba.Models.Paquete", null)
                        .WithMany("DetalleReservaPaquetes")
                        .HasForeignKey("PaqueteIdPaquete");

                    b.Navigation("IdPaqueteNavigation");

                    b.Navigation("IdReservaNavigation");
                });

            modelBuilder.Entity("OctavaPrueba.Models.DetalleReservaServicio", b =>
                {
                    b.HasOne("OctavaPrueba.Models.Reserva", "IdReservaNavigation")
                        .WithMany("DetalleReservaServicios")
                        .HasForeignKey("IdReserva")
                        .IsRequired()
                        .HasConstraintName("FK__DetalleRe__IdRes__114A936A");

                    b.HasOne("OctavaPrueba.Models.Servicio", "IdServicioNavigation")
                        .WithMany()
                        .HasForeignKey("IdServicio")
                        .IsRequired()
                        .HasConstraintName("FK__DetalleRe__IdSer__10566F31");

                    b.HasOne("OctavaPrueba.Models.Servicio", null)
                        .WithMany("DetalleReservaServicios")
                        .HasForeignKey("ServicioIdServicio");

                    b.Navigation("IdReservaNavigation");

                    b.Navigation("IdServicioNavigation");
                });

            modelBuilder.Entity("OctavaPrueba.Models.HabitacionMueble", b =>
                {
                    b.HasOne("OctavaPrueba.Models.Habitacione", "IdHabitacionNavigation")
                        .WithMany("HabitacionMuebles")
                        .HasForeignKey("IdHabitacion")
                        .IsRequired()
                        .HasConstraintName("FK__Habitacio__IdHab__628FA481");

                    b.HasOne("OctavaPrueba.Models.Mueble", "IdMuebleNavigation")
                        .WithMany("HabitacionMuebles")
                        .HasForeignKey("IdMueble")
                        .IsRequired()
                        .HasConstraintName("FK__Habitacio__IdMue__6383C8BA");

                    b.Navigation("IdHabitacionNavigation");

                    b.Navigation("IdMuebleNavigation");
                });

            modelBuilder.Entity("OctavaPrueba.Models.Habitacione", b =>
                {
                    b.HasOne("OctavaPrueba.Models.TipoHabitacione", "IdTipoHabitacionNavigation")
                        .WithMany("Habitaciones")
                        .HasForeignKey("IdTipoHabitacion")
                        .IsRequired()
                        .HasConstraintName("FK__Habitacio__IdTip__5BE2A6F2");

                    b.Navigation("IdTipoHabitacionNavigation");
                });

            modelBuilder.Entity("OctavaPrueba.Models.ImagenAbono", b =>
                {
                    b.HasOne("OctavaPrueba.Models.Abono", "IdAbonoNavigation")
                        .WithMany("ImagenAbonos")
                        .HasForeignKey("IdAbono")
                        .IsRequired()
                        .HasConstraintName("FK__ImagenAbo__IdAbo__1DB06A4F");

                    b.HasOne("OctavaPrueba.Models.Imagene", "IdImagenNavigation")
                        .WithMany("ImagenAbonos")
                        .HasForeignKey("IdImagen")
                        .IsRequired()
                        .HasConstraintName("FK__ImagenAbo__IdIma__1CBC4616");

                    b.Navigation("IdAbonoNavigation");

                    b.Navigation("IdImagenNavigation");
                });

            modelBuilder.Entity("OctavaPrueba.Models.ImagenHabitacion", b =>
                {
                    b.HasOne("OctavaPrueba.Models.Habitacione", "IdHabitacionNavigation")
                        .WithMany("ImagenHabitacions")
                        .HasForeignKey("IdHabitacion")
                        .IsRequired()
                        .HasConstraintName("FK__ImagenHab__IdHab__6754599E");

                    b.HasOne("OctavaPrueba.Models.Imagene", "IdImagenNavigation")
                        .WithMany("ImagenHabitacions")
                        .HasForeignKey("IdImagen")
                        .IsRequired()
                        .HasConstraintName("FK__ImagenHab__IdIma__66603565");

                    b.Navigation("IdHabitacionNavigation");

                    b.Navigation("IdImagenNavigation");
                });

            modelBuilder.Entity("OctavaPrueba.Models.ImagenPaquete", b =>
                {
                    b.HasOne("OctavaPrueba.Models.Imagene", "IdImagenNavigation")
                        .WithMany("ImagenPaquetes")
                        .HasForeignKey("IdImagen")
                        .IsRequired()
                        .HasConstraintName("FK__ImagenPaq__IdIma__778AC167");

                    b.HasOne("OctavaPrueba.Models.Paquete", "IdPaqueteNavigation")
                        .WithMany("ImagenPaquetes")
                        .HasForeignKey("IdPaquete")
                        .IsRequired()
                        .HasConstraintName("FK__ImagenPaq__IdPaq__787EE5A0");

                    b.Navigation("IdImagenNavigation");

                    b.Navigation("IdPaqueteNavigation");
                });

            modelBuilder.Entity("OctavaPrueba.Models.ImagenServicio", b =>
                {
                    b.HasOne("OctavaPrueba.Models.Imagene", "IdImagenNavigation")
                        .WithMany("ImagenServicios")
                        .HasForeignKey("IdImagen")
                        .IsRequired()
                        .HasConstraintName("FK__ImagenSer__IdIma__6FE99F9F");

                    b.HasOne("OctavaPrueba.Models.Servicio", "IdServicioNavigation")
                        .WithMany("ImagenServicios")
                        .HasForeignKey("IdServicio")
                        .IsRequired()
                        .HasConstraintName("FK__ImagenSer__IdSer__70DDC3D8");

                    b.Navigation("IdImagenNavigation");

                    b.Navigation("IdServicioNavigation");
                });

            modelBuilder.Entity("OctavaPrueba.Models.Paquete", b =>
                {
                    b.HasOne("OctavaPrueba.Models.Habitacione", "IdHabitacionNavigation")
                        .WithMany("Paquetes")
                        .HasForeignKey("IdHabitacion")
                        .IsRequired()
                        .HasConstraintName("FK__Paquetes__IdHabi__74AE54BC");

                    b.Navigation("IdHabitacionNavigation");
                });

            modelBuilder.Entity("OctavaPrueba.Models.PaqueteServicio", b =>
                {
                    b.HasOne("OctavaPrueba.Models.Paquete", "IdPaqueteNavigation")
                        .WithMany("PaqueteServicios")
                        .HasForeignKey("IdPaquete")
                        .IsRequired()
                        .HasConstraintName("FK__PaqueteSe__IdPaq__7B5B524B");

                    b.HasOne("OctavaPrueba.Models.Servicio", "IdServicioNavigation")
                        .WithMany("PaqueteServicios")
                        .HasForeignKey("IdServicio")
                        .IsRequired()
                        .HasConstraintName("FK__PaqueteSe__IdSer__7C4F7684");

                    b.Navigation("IdPaqueteNavigation");

                    b.Navigation("IdServicioNavigation");
                });

            modelBuilder.Entity("OctavaPrueba.Models.PermisosRole", b =>
                {
                    b.HasOne("OctavaPrueba.Models.Permiso", "IdPermisoNavigation")
                        .WithMany("PermisosRoles")
                        .HasForeignKey("IdPermiso")
                        .HasConstraintName("FK__PermisosR__IdPer__4E88ABD4");

                    b.HasOne("OctavaPrueba.Models.Role", "IdRolNavigation")
                        .WithMany("PermisosRoles")
                        .HasForeignKey("IdRol")
                        .HasConstraintName("FK__PermisosR__IdRol__4D94879B");

                    b.Navigation("IdPermisoNavigation");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("OctavaPrueba.Models.Reserva", b =>
                {
                    b.HasOne("OctavaPrueba.Models.EstadosReserva", "IdEstadoReservaNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("IdEstadoReserva")
                        .IsRequired()
                        .HasConstraintName("FK__Reservas__IdEsta__0C85DE4D");

                    b.HasOne("OctavaPrueba.Models.MetodoPago", "MetodoPagoNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("MetodoPago")
                        .IsRequired()
                        .HasConstraintName("FK__Reservas__Metodo__0D7A0286");

                    b.HasOne("OctavaPrueba.Models.Cliente", "NroDocumentoClienteNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("NroDocumentoCliente")
                        .HasConstraintName("FK__Reservas__NroDoc__0A9D95DB");

                   

                    b.Navigation("IdEstadoReservaNavigation");

                    b.Navigation("MetodoPagoNavigation");

                    b.Navigation("NroDocumentoClienteNavigation");
                });

            modelBuilder.Entity("OctavaPrueba.Models.Servicio", b =>
                {
                    b.HasOne("OctavaPrueba.Models.TipoServicio", "IdTipoServicioNavigation")
                        .WithMany("Servicios")
                        .HasForeignKey("IdTipoServicio")
                        .IsRequired()
                        .HasConstraintName("FK__Servicios__IdTip__6D0D32F4");

                    b.Navigation("IdTipoServicioNavigation");
                });

            modelBuilder.Entity("OctavaPrueba.Models.Usuario", b =>
                {
                    b.HasOne("OctavaPrueba.Models.Role", "IdRolNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .HasConstraintName("FK__Usuarios__IdRol__5441852A");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("OctavaPrueba.Models.Abono", b =>
                {
                    b.Navigation("ImagenAbonos");
                });

            modelBuilder.Entity("OctavaPrueba.Models.Cliente", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("OctavaPrueba.Models.EstadosReserva", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("OctavaPrueba.Models.Habitacione", b =>
                {
                    b.Navigation("HabitacionMuebles");

                    b.Navigation("ImagenHabitacions");

                    b.Navigation("Paquetes");
                });

            modelBuilder.Entity("OctavaPrueba.Models.Imagene", b =>
                {
                    b.Navigation("ImagenAbonos");

                    b.Navigation("ImagenHabitacions");

                    b.Navigation("ImagenPaquetes");

                    b.Navigation("ImagenServicios");
                });

            modelBuilder.Entity("OctavaPrueba.Models.MetodoPago", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("OctavaPrueba.Models.Mueble", b =>
                {
                    b.Navigation("HabitacionMuebles");
                });

            modelBuilder.Entity("OctavaPrueba.Models.Paquete", b =>
                {
                    b.Navigation("DetalleReservaPaquetes");

                    b.Navigation("ImagenPaquetes");

                    b.Navigation("PaqueteServicios");
                });

            modelBuilder.Entity("OctavaPrueba.Models.Permiso", b =>
                {
                    b.Navigation("PermisosRoles");
                });

            modelBuilder.Entity("OctavaPrueba.Models.Reserva", b =>
                {
                    b.Navigation("Abonos");

                    b.Navigation("DetalleReservaPaquetes");

                    b.Navigation("DetalleReservaServicios");
                });

            modelBuilder.Entity("OctavaPrueba.Models.Role", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("PermisosRoles");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("OctavaPrueba.Models.Servicio", b =>
                {
                    b.Navigation("DetalleReservaServicios");

                    b.Navigation("ImagenServicios");

                    b.Navigation("PaqueteServicios");
                });

            modelBuilder.Entity("OctavaPrueba.Models.TipoDocumento", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("OctavaPrueba.Models.TipoHabitacione", b =>
                {
                    b.Navigation("Habitaciones");
                });

            modelBuilder.Entity("OctavaPrueba.Models.TipoServicio", b =>
                {
                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("OctavaPrueba.Models.Usuario", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
